CREATE DATABASE sdg_hack;
# GRANT PRIVILEGES ACCORDING TO LOCAL SERVER
CREATE TABLE nodes
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name TEXT NOT NULL
);

CREATE TABLE links
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	source INT, target INT, value INT
);

